# 19.1 Numpy nedir

In [ ]:
import numpy as np

# python list

py_list = [1,2,3,4,5,6,7,8,9]

#numpy array

np_array = np.array([1,2,3,4,5,6,7,8,9])

print (type(py_list))
print (type(np_array))

py_multi = [[1,2,3],[4,5,6],[7,8,9]]
np_multi = np_array.reshape(3,3)

print (py_multi)
print (np_multi)



<class 'list'>
<class 'numpy.ndarray'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 19.2 Numpy dizileri ile Çalısma

In [23]:

result = np.array([1,3,5,7,9])
result = np.arange(1,10)
result = np.arange(10,100,3)
result = np.zeros(10)
result = np.ones(10)
result = np.linspace(0,100,5)
result = np.linspace(0,5,5)
result = np.random.randint(0,10)
result = np.random.randint(20)
result = np.random.randint(1,10,3)
result = np.random.rand(5)
result = np.random.randn(5)

np_array = np.arange (50)
np_multi = np_array.reshape(5,10)
print(np_multi.sum(axis=1))

rnd_numbers = np.random.randint(1,100,10)
result = rnd_numbers.max()
result = rnd_numbers.min()
result = rnd_numbers.mean()
result = rnd_numbers.argmax()



print(result)

[ 45 145 245 345 445]
2


# 19.3 Numpy Dizilerinin Indekslenmesi

In [35]:
numberss = np.array([0,5,10,15,20,25,50,75])
result   = numberss[5]
result   = numberss[-1]
result   = numberss[0:3]


numberss2 = np.array([[0,5,10],[15,20,25],[50,75,85]])
result = numberss2[0]
result = numberss2[2]
result = numberss2[0,2]
result = numberss2[2,1]
result = numberss2[:,2]
result = numberss2[:,0]
result = numberss2[:2,:2]

print(result)

arr1 = np.arange(0,10)
#arr2 = arr1 #referans
arr2 = arr1.copy()
arr2[0] = 20

print(arr1)
print(arr2)

[[ 0  5]
 [15 20]]
[0 1 2 3 4 5 6 7 8 9]
[20  1  2  3  4  5  6  7  8  9]


# 19.4 Numpy Dizi Operasyonları

In [ ]:
numbers1 = np.random.randint(10,100,6)
numbers2 = np.random.randint(10,100,6)
print(numbers1)
print(numbers2)

result = numbers1 + numbers2
result = numbers1 + 10
result = numbers1 - numbers2
result = numbers1 - 10
result = numbers1 * numbers2
result = numbers1 * 10
result = numbers1 / numbers2
result = numbers1 / 10

result = np.sin(numbers1)
result = np.cos(numbers1)
result = np.sqrt(numbers1)
result = np.log(numbers1)

mnumbers1 = numbers1.reshape(2,3)
mnumbers2 = numbers2.reshape(2,3)

print (mnumbers1)
print (mnumbers2)

result = np.vstack((mnumbers1,mnumbers2))
result = np.hstack((mnumbers1,mnumbers2))

result = numbers1 >=50
result = numbers1 % 2 == 0

print(result)

[18 37 33 17 55 83]
[40 54 66 43 18 30]
[[18 37 33]
 [17 55 83]]
[[40 54 66]
 [43 18 30]]
[ True False False False False False]


# 19.5 Demo-Numpy

In [47]:
result = np.array([10,15,30,45,60])
print(result)

[10 15 30 45 60]


In [48]:
result = np.arange(5,15)
print(result)

[ 5  6  7  8  9 10 11 12 13 14]


In [49]:
result = np.arange(50,100,5)
print (result)

[50 55 60 65 70 75 80 85 90 95]


In [51]:
result = np.zeros(10)
print(result)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [52]:
result = np.ones(10)
print(result)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [56]:
result = np.linspace(0,100,5)
print(result)

[  0.  25.  50.  75. 100.]


In [54]:
result = np.random.randint(10,30,5)
print(result)


[21 20 27 16 16]


In [255]:

result = np.linspace(-1,1,10)
result = np.random.randn(10)
print(result)

[ 0.28585107 -0.31324179  0.23776675 -0.31797734  0.2717032   0.09971207
  1.65643983  1.54580689 -0.63784824  0.17095717]


In [ ]:
result = np.random.randint(10,50,15).reshape(3,5)
print (result)

[[42 36 30 46 33]
 [45 37 20 19 19]
 [16 39 43 12 43]]


In [257]:
matris = np.random.randint(10,50,15).reshape(3,5)
rowTotal = matris.sum(axis=1)
colTotal = matris.sum(axis=0)
print(matris)
print(rowTotal)
print(colTotal)


[[10 20 12 19 24]
 [15 12 38 12 27]
 [11 43 21 11 34]]
[ 85 104 120]
[36 75 71 42 85]


In [261]:
matris = np.random.randint(10,50,15).reshape(3,5)
result = matris.max()
result = matris.min()
result = matris.mean()

print(matris)
print(result)

[[25 20 14 21 40]
 [35 46 42 18 17]
 [37 23 10 17 24]]
25.933333333333334


In [264]:
result = matris.argmax()
result = matris.argmin()
print(result)

12
