# 19.1 Numpy nedir

In [ ]:
import numpy as np

# python list

py_list = [1,2,3,4,5,6,7,8,9]

#numpy array

np_array = np.array([1,2,3,4,5,6,7,8,9])

print (type(py_list))
print (type(np_array))

py_multi = [[1,2,3],[4,5,6],[7,8,9]]
np_multi = np_array.reshape(3,3)

print (py_multi)
print (np_multi)



<class 'list'>
<class 'numpy.ndarray'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 19.2 Numpy dizileri ile Çalısma

In [23]:

result = np.array([1,3,5,7,9])
result = np.arange(1,10)
result = np.arange(10,100,3)
result = np.zeros(10)
result = np.ones(10)
result = np.linspace(0,100,5)
result = np.linspace(0,5,5)
result = np.random.randint(0,10)
result = np.random.randint(20)
result = np.random.randint(1,10,3)
result = np.random.rand(5)
result = np.random.randn(5)

np_array = np.arange (50)
np_multi = np_array.reshape(5,10)
print(np_multi.sum(axis=1))

rnd_numbers = np.random.randint(1,100,10)
result = rnd_numbers.max()
result = rnd_numbers.min()
result = rnd_numbers.mean()
result = rnd_numbers.argmax()



print(result)

[ 45 145 245 345 445]
2


# 19.3 Numpy Dizilerinin Indekslenmesi

In [ ]:
numberss = np.array([0,5,10,15,20,25,50,75])
result   = numberss[5]
result   = numberss[-1]
result   = numberss[0:3]


numberss2 = np.array([[0,5,10],[15,20,25],[50,75,85]])
result = numberss2[0]
result = numberss2[2]
result = numberss2[0,2]
result = numberss2[2,1]
result = numberss2[:,2]
result = numberss2[:,0]
result = numberss2[:2,:2]

print(result)

arr1 = np.arange(0,10)
#arr2 = arr1 #referans
arr2 = arr1.copy()
arr2[0] = 20

print(arr1)
print(arr2)

[[ 0  5]
 [15 20]]
[20  1  2  3  4  5  6  7  8  9]
[20  1  2  3  4  5  6  7  8  9]
